In [ ]:
import pickle
import pandas as pd

In [3]:
with open('../data_and_models/search_results_tree_k4_n5.pkl', 'rb') as f:
    search_k5_n5 = pickle.load(f)

In [4]:
search_k5_n5

,search_id,type_of_search,n_steps,k,n_paths,beta,blend,threshold,starting_cl,target_cl,...,step,path_type,is_best_at_step,is_success,covered_threshold,end_position,drug_sequence,genes_targeted,cell_path,final_distance
0,1,k_pathtree,5,4,None,None,2,0.4,CVCL_0023,CVCL_0069,...,1.0,best_at_step,True,False,False,"[0.22140636999999996, 0.3578622, 0.5259334, -1...","[[('Abemaciclib', 5.0, 'uM')]]","[(cdk4, cdk6)]","[[CVCL_0023, None]]",6.828595
1,1,k_pathtree,5,4,None,None,2,0.4,CVCL_0023,CVCL_0069,...,2.0,best_at_step,True,False,False,"[-0.505162765, 0.62511613, 1.31767136, -1.3214...","[[('TAK-733', 5.0, 'uM')], [('Rosiglitazone', ...","[(map2k2, map2k1), (pparg,)]","[[CVCL_0023, None], [CVCL_0023, None]]",6.591480
2,1,k_pathtree,5,4,None,None,2,0.4,CVCL_0023,CVCL_0069,...,3.0,best_at_step,True,False,False,"[-0.13686981232727558, 0.6059813486540502, 0.7...","[[('Abemaciclib', 5.0, 'uM')], [('Rosiglitazon...","[(cdk4, cdk6), (pparg,), (slc46a1, folr1, slc1...","[[CVCL_0023, None], [None, CVCL_0023], [CVCL_1...",6.507877
3,1,k_pathtree,5,4,None,None,2,0.4,CVCL_0023,CVCL_0069,...,4.0,best_at_step,True,False,False,"[-0.49210860200686446, 0.5411713256362565, 1.5...","[[('Abemaciclib', 5.0, 'uM')], [('Macitentan',...","[(cdk4, cdk6), (ednrb, ednra), (slc46a1, folr1...","[[CVCL_0023, None], [None, CVCL_0023], [CVCL_1...",6.419707
4,1,k_pathtree,5,4,None,None,2,0.4,CVCL_0023,CVCL_0069,...,5.0,best_at_step,True,False,False,"[-0.5990250697000296, 0.6466211312575441, 1.45...","[[('Abemaciclib', 5.0, 'uM')], [('Macitentan',...","[(cdk4, cdk6), (ednrb, ednra), (slc46a1, folr1...","[[CVCL_0023, None], [None, CVCL_0023], [CVCL_1...",6.385758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77037,2254,k_pathtree,5,4,None,None,2,0.4,CVCL_C466,CVCL_1724,...,5.0,threshold,False,False,True,"[-0.3704120905298948, 0.25842389545635885, 0.3...","[[('vincristine', 5.0, 'uM')], [('olaparib', 5...","[(tubb1, tubb4b, tubb8, tuba3c, tuba1c, tubb2a...","[[CVCL_C466, None], [CVCL_C466, CVCL_1715], [C...",5.582089
77038,2254,k_pathtree,5,4,None,None,2,0.4,CVCL_C466,CVCL_1724,...,5.0,threshold,False,False,True,"[-0.3662882675182758, 0.32858954614592006, 0.3...","[[('vincristine', 5.0, 'uM')], [('olaparib', 5...","[(tubb1, tubb4b, tubb8, tuba3c, tuba1c, tubb2a...","[[CVCL_C466, None], [CVCL_C466, CVCL_1715], [C...",5.562641
77039,2254,k_pathtree,5,4,None,None,2,0.4,CVCL_C466,CVCL_1724,...,1.0,best_at_step,True,False,False,"[0.22615593999999994, 0.93932086, 1.5589155, 0...","[[('Bortezomib', 5.0, 'uM')]]","[(psmb1, psmd8, psmb7, psmd3, psma3, psmb3, ps...","[[CVCL_C466, None]]",6.651125
77040,2254,k_pathtree,5,4,None,None,2,0.4,CVCL_C466,CVCL_1724,...,2.0,best_at_step,True,False,False,"[-0.5010930965521725, 0.663907391526372, 1.519...","[[('vincristine', 5.0, 'uM')], [('olaparib', 5...","[(tubb1, tubb4b, tubb8, tuba3c, tuba1c, tubb2a...","[[CVCL_C466, None], [CVCL_C466, CVCL_1715]]",6.156743
77041,2254,k_pathtree,5,4,None,None,2,0.4,CVCL_C466,CVCL_1724,...,3.0,best_at_step,True,False,False,"[-0.3522973873770415, 0.5100059583947778, 1.03...","[[('vincristine', 5.0, 'uM')], [('olaparib', 5...","[(tubb1, tubb4b, tubb8, tuba3c, tuba1c, tubb2a...","[[CVCL_C466, None], [CVCL_C466, CVCL_1715], [C...",5.743894

In [9]:
search_k5_n5[(search_k5_n5['starting_distance'] - search_k5_n5['final_distance'])/search_k5_n5['starting_distance'] > 0.62]

,search_id,type_of_search,n_steps,k,n_paths,beta,blend,threshold,starting_cl,target_cl,...,step,path_type,is_best_at_step,is_success,covered_threshold,end_position,drug_sequence,genes_targeted,cell_path,final_distance
28640,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7102991837994095, -0.25872653413824553, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.309488
28641,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.6837426813267942, -0.25129894275648906, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.317571
28642,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7564924550136833, -0.22929529726317271, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.326012
28643,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7115436493209544, -0.3523108053979763, 1.4...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.330598
28644,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7115126808922626, -0.2636270524249316, 1.5...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.310641
28645,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7508563610061989, -0.3988836890020219, 1.3...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.328636
28646,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7250204245739627, -0.29708976508328716, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.331686
28647,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7491980838929722, -0.2652135922334289, 1.3...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.346121
28648,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7498373670995415, -0.2620003663349241, 1.3...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.344498
28652,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7509200884250259, -0.39579783133194435, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.326869
28653,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7135557311226107, -0.35478215503175997, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (cck...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.329556
28656,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7518872493739106, -0.3894735853068653, 1.6...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.269864
28657,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7982868764405424, -0.35973325813492396, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.275035
28658,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7711682226710113, -0.4530605002301484, 1.4...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.277651
28659,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7257022792054553, -0.3817433439948751, 1.6...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.287480
28660,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7531113735714918, -0.3944679984494917, 1.6...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.271902
28661,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7910602815517629, -0.3961564552016983, 1.5...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.306124
28662,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7926430184081894, -0.5299462170273457, 1.5...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.307216
28663,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8323839013991733, -0.41323875959469897, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.309272
28664,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7539920963594088, -0.35085603690334316, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.294736
28665,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7916869150283316, -0.3928495350355392, 1.5...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.304048
28668,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.755203434186196, -0.4854096916475238, 1.57...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.287789
28669,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7927013834910815, -0.5268206612855595, 1.5...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (gnr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.304933
28672,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7277889233565724, -0.3236492320744661, 1.4...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (adr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.344082
28676,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7289736695441505, -0.3284936590885648, 1.4...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (adr...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.345788
28688,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,True,False,True,"[-0.7634477927170226, -0.3897354278899749, 1.6...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.258564
28689,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8096998232999806, -0.36021617824229163, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.265097
28690,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7827929742761607, -0.4537018457597607, 1.4...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.268241
28691,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7369970832393176, -0.3822216576156421, 1.6...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.277043
28692,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7222362124325246, -0.259707580289799, 1.52...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.298665
28693,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.6953642896807526, -0.2525369300257118, 1.5...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.306693
28694,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7682542934417274, -0.23053875221910558, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.316328
28695,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7234535032996514, -0.3534340740307089, 1.4...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.319438
28696,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.7390811969098673, -0.3273573781858274, 1.4...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.333199
28700,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8094107303875384, -0.15840546905703093, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.278442
28701,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.5991632777868582, -0.25275193636982807, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.302042
28702,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8105855443702858, -0.2523542717111001, 1.5...","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.314070
28703,901,k_pathtree,5,4,None,None,2,0.4,CVCL_0459,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8354930786846118, -0.32977921459029114, 1....","[[('TAK-733', 5.0, 'uM')], [('olaparib', 5.0, ...","[(map2k2, map2k1), (parp3, parp2, parp1), (ptg...","[[CVCL_0459, None], [CVCL_0459, None], [CVCL_0...",3.325957
39692,1230,k_pathtree,5,4,None,None,2,0.4,CVCL_1097,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8537655703312217, 0.3622276912474907, 1.25...","[[('Doxorubicin (hydrochloride)', 5.0, 'uM')],...","[(top2a, top2b, top1), (parp3, parp2, parp1), ...","[[CVCL_1097, CVCL_0069], [None, CVCL_1097], [C...",3.318650
39708,1230,k_pathtree,5,4,None,None,2,0.4,CVCL_1097,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8396081645353489, 0.36376964843805126, 1.2...","[[('Doxorubicin (hydrochloride)', 5.0, 'uM')],...","[(top2a, top2b, top1), (parp3, parp2, parp1), ...","[[CVCL_1097, CVCL_0069], [None, CVCL_1097], [C...",3.328041
39712,1230,k_pathtree,5,4,None,None,2,0.4,CVCL_1097,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8445415360098179, 0.36880620846030976, 1.2...","[[('Doxorubicin (hydrochloride)', 5.0, 'uM')],...","[(top2a, top2b, top1), (parp3, parp2, parp1), ...","[[CVCL_1097, CVCL_0069], [None, CVCL_1097], [C...",3.324306
39948,1230,k_pathtree,5,4,None,None,2,0.4,CVCL_1097,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.852919320240034, 0.22936899780452288, 1.20...","[[('venetoclax', 5.0, 'uM')], [('olaparib', 5....","[(bcl2,), (parp3, parp2, parp1), (jak3, tyk2, ...","[[CVCL_1097, CVCL_0069], [CVCL_1097, None], [C...",3.326598
39952,1230,k_pathtree,5,4,None,None,2,0.4,CVCL_1097,CVCL_0292,...,5.0,threshold,True,False,True,"[-0.9268234577002623, 0.32951333811059447, 1.2...","[[('venetoclax', 5.0, 'uM')], [('olaparib', 5....","[(bcl2,), (parp3, parp2, parp1), (jak3, tyk2, ...","[[CVCL_1097, CVCL_0069], [CVCL_1097, None], [C...",3.308954
39953,1230,k_pathtree,5,4,None,None,2,0.4,CVCL_1097,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8882950768818118, 0.3739733129652003, 1.27...","[[('venetoclax', 5.0, 'uM')], [('olaparib', 5....","[(bcl2,), (parp3, parp2, parp1), (jak3, tyk2, ...","[[CVCL_1097, CVCL_0069], [CVCL_1097, None], [C...",3.344100
39956,1230,k_pathtree,5,4,None,None,2,0.4,CVCL_1097,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8113525627262221, 0.35997644377063376, 1.0...","[[('venetoclax', 5.0, 'uM')], [('olaparib', 5....","[(bcl2,), (parp3, parp2, parp1), (jak3, tyk2, ...","[[CVCL_1097, CVCL_0069], [CVCL_1097, None], [C...",3.369314
39980,1230,k_pathtree,5,4,None,None,2,0.4,CVCL_1097,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8387173853278244, 0.22957057943884016, 1.2...","[[('venetoclax', 5.0, 'uM')], [('olaparib', 5....","[(bcl2,), (parp3, parp2, parp1), (gnrhr,), (ja...","[[CVCL_1097, CVCL_0069], [CVCL_1097, None], [C...",3.338638
39988,1230,k_pathtree,5,4,None,None,2,0.4,CVCL_1097,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.8425232045982104, 0.22413337879862877, 1.2...","[[('venetoclax', 5.0, 'uM')], [('olaparib', 5....","[(bcl2,), (parp3, parp2, parp1), (gnrhr,), (sm...","[[CVCL_1097, CVCL_0069], [CVCL_1097, None], [C...",3.338422

In [10]:
search_k5_n5[search_k5_n5['path_type'] == 'threshold'][['starting_cl', 'target_cl']].drop_duplicates().shape[0]

207

In [11]:
search_k5_n5[search_k5_n5['path_type'] == 'threshold'] ['target_cl'].drop_duplicates().shape[0]

25

In [12]:
with open('../data_and_models/probabilistic_search_results_paths300_steps5_b1.0_blend2_thr0.4.pkl', 'rb') as f:
    search_paths300_n5 = pickle.load(f)

In [13]:
search_paths300_n5

,search_id,type_of_search,n_steps,k,n_paths,beta,blend,threshold,starting_cl,target_cl,...,step,path_type,is_best_at_step,is_success,covered_threshold,end_position,drug_sequence,genes_targeted,cell_path,final_distance
0,0,probabilistic,5,None,300,1.0,2,None,CVCL_0023,CVCL_0028,...,1,best_at_step,True,False,False,"[-0.48289399999999993, 0.25001379999999995, 1....","[[('venetoclax', 5.0, 'uM')]]","[(bcl2,)]","[[CVCL_0023, None]]",4.997213
1,0,probabilistic,5,None,300,1.0,2,None,CVCL_0023,CVCL_0028,...,2,best_at_step,True,False,False,"[-0.6189341130965526, 0.07904840032552318, 1.4...","[[('venetoclax', 5.0, 'uM')], [('Perindopril (...","[(bcl2,), (ace,)]","[[CVCL_0023, None], [CVCL_1716, CVCL_0292]]",4.944891
2,0,probabilistic,5,None,300,1.0,2,None,CVCL_0023,CVCL_0028,...,3,best_at_step,True,False,False,"[-0.5713501924402727, 0.6176319674016477, 1.85...","[[('Cabozantinib (S-malate)', 5.0, 'uM')], [('...","[(met, ret, kdr), (plk1,), (cdk4, cdk6)]","[[CVCL_0023, CVCL_1716], [CVCL_0023, None], [C...",4.957154
3,0,probabilistic,5,None,300,1.0,2,None,CVCL_0023,CVCL_0028,...,4,best_at_step,True,False,False,"[-1.1020077777576105, 0.20192637437692024, 2.2...","[[('Vemurafenib', 5.0, 'uM')], [('venetoclax',...","[(braf,), (bcl2,), (aldh2,), (esr1, esr2)]","[[CVCL_0023, CVCL_1716], [CVCL_0023, None], [C...",4.952572
4,0,probabilistic,5,None,300,1.0,2,None,CVCL_0023,CVCL_0028,...,5,best_at_step,True,False,False,"[-0.9513206328523165, -0.22347274684681784, 1....","[[('venetoclax', 5.0, 'uM')], [('Perindopril (...","[(bcl2,), (ace,), (slc5a2,), (pdgfra, flt3, ki...","[[CVCL_0023, None], [CVCL_1716, CVCL_0292], [C...",5.101539
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13944,2255,probabilistic,5,None,300,1.0,2,None,CVCL_C466,CVCL_1731,...,1,best_at_step,True,False,False,"[1.2403478999999997, 1.2032412, 0.6653516, -0....","[[('Niclosamide (olamine)', 5.0, 'uM')]]","[(stat3,)]","[[CVCL_C466, None]]",5.736268
13945,2255,probabilistic,5,None,300,1.0,2,None,CVCL_C466,CVCL_1731,...,2,best_at_step,True,False,False,"[1.6544984660645294, 1.3936924512826105, 0.408...","[[('venetoclax', 5.0, 'uM')], [('Folic acid', ...","[(bcl2,), (slc46a1, folr1, slc19a1, folr2)]","[[CVCL_C466, None], [CVCL_1715, CVCL_1716]]",5.366413
13946,2255,probabilistic,5,None,300,1.0,2,None,CVCL_C466,CVCL_1731,...,3,best_at_step,True,False,False,"[1.3697940660645291, 1.1344339512826105, 0.538...","[[('venetoclax', 5.0, 'uM')], [('Folic acid', ...","[(bcl2,), (slc46a1, folr1, slc19a1, folr2), (t...","[[CVCL_C466, None], [CVCL_1715, CVCL_1716], [N...",5.367665
13947,2255,probabilistic,5,None,300,1.0,2,None,CVCL_C466,CVCL_1731,...,4,best_at_step,True,False,False,"[0.8856916043253285, 0.9570598782614838, 0.747...","[[('Irinotecan', 5.0, 'uM')], [('Mifepristone'...","[(top1mt, top1), (klk3, nr3c1, pgr), (pde5a,),...","[[CVCL_C466, CVCL_1715], [CVCL_C466, None], [C...",5.554464
13948,2255,probabilistic,5,None,300,1.0,2,None,CVCL_C466,CVCL_1731,...,5,best_at_step,True,False,False,"[0.140902041839436, 0.6324256495782987, 0.6182...","[[('Bexarotene', 5.0, 'uM')], [('vincristine',...","[(rxrg, rxra, rxrb), (tubb1, tubb4b, tubb8, tu...","[[CVCL_C466, None], [CVCL_C466, None], [CVCL_1...",5.449431

In [18]:
search_paths300_n5[(search_paths300_n5['starting_distance'] - search_paths300_n5['final_distance'])/search_paths300_n5['starting_distance'] > 0.57]

,search_id,type_of_search,n_steps,k,n_paths,beta,blend,threshold,starting_cl,target_cl,...,step,path_type,is_best_at_step,is_success,covered_threshold,end_position,drug_sequence,genes_targeted,cell_path,final_distance
5224,901,probabilistic,5,None,300,1.0,2,None,CVCL_0459,CVCL_0292,...,5,threshold,True,False,True,"[-0.6708116737706488, 0.057514088912868334, 1....","[[('Doxorubicin (hydrochloride)', 5.0, 'uM')],...","[(top2a, top2b, top1), (rps6kb1,), (alox5,), (...","[[CVCL_0459, None], [None, CVCL_0459], [CVCL_1...",3.717137
7769,1230,probabilistic,5,None,300,1.0,2,None,CVCL_1097,CVCL_0292,...,4,threshold,True,False,True,"[-0.6617480816592507, 0.7267932709232893, 1.45...","[[('olaparib', 5.0, 'uM')], [('venetoclax', 5....","[(parp3, parp2, parp1), (bcl2,), (ptgs2,), (ca...","[[CVCL_1097, CVCL_0069], [CVCL_1097, None], [C...",3.793680

In [19]:
search_paths300_n5[search_paths300_n5['path_type'] == 'threshold'][['starting_cl', 'target_cl']].drop_duplicates().shape[0]

64

In [20]:
search_paths300_n5[search_paths300_n5['path_type'] == 'threshold'] ['target_cl'].drop_duplicates().shape[0]

10